# python fedtrain.py data=ml-1m-v2 net=fedmf task_name=fedtrain TRAIN.wandb=True TRAIN.lr=1e-1 FED.agg_epochs=2000 TRAIN.weight_decay=1e-4 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=1
# python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=64 task_name=fedtrain TRAIN.wandb=True FED.agg_epochs=2000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=64 FED.local_epochs=2 TRAIN.weight_decay=1e-4 TRAIN.lr=1e-1 EXP.project=lora-fedrec
# python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=32 task_name=fedtrain TRAIN.wandb=True FED.agg_epochs=2000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=64 FED.local_epochs=2 TRAIN.weight_decay=1e-4 TRAIN.lr=1e-1 EXP.project=lora-fedrec
# python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=16 task_name=fedtrain TRAIN.wandb=True FED.agg_epochs=2000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=64 FED.local_epochs=2 TRAIN.weight_decay=1e-4 TRAIN.lr=1e-1 EXP.project=lora-fedrec
# python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=4 task_name=fedtrain TRAIN.wandb=True FED.agg_epochs=2000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=64 FED.local_epochs=2 TRAIN.weight_decay=1e-4 TRAIN.lr=1e-1 EXP.project=lora-fedrec
# python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=2 task_name=fedtrain TRAIN.wandb=True FED.agg_epochs=2000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=64 FED.local_epochs=2 TRAIN.weight_decay=1e-4 TRAIN.lr=1e-1 EXP.project=lora-fedrec
# python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=8 task_name=fedtrain TRAIN.wandb=True FED.agg_epochs=2000 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=64 FED.local_epochs=2 TRAIN.weight_decay=1e-4 TRAIN.lr=1e-1 EXP.project=lora-fedrec


python fedtrain.py data=ml-1m net=fedmf-lora-b net.init.gmf_emb_size=64 net.init.lora_rank=2 task_name=fedtrain-nb-scaling-init TRAIN.wandb=True TRAIN.lr=0.02416 FED.agg_epochs=2000 TRAIN.weight_decay=1e-4 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=64 FED.local_epochs=2 EXP.project=lora-fedrec
python fedtrain.py data=ml-1m net=fedmf-lora-b net.init.gmf_emb_size=64 net.init.lora_rank=4 task_name=fedtrain-nb-scaling-init TRAIN.wandb=True TRAIN.lr=0.02416 FED.agg_epochs=2000 TRAIN.weight_decay=1e-4 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=64 FED.local_epochs=2 EXP.project=lora-fedrec
python fedtrain.py data=ml-1m net=fedmf-lora-b net.init.gmf_emb_size=64 net.init.lora_rank=8 task_name=fedtrain-nb-scaling-init TRAIN.wandb=True TRAIN.lr=0.01 FED.agg_epochs=2000 TRAIN.weight_decay=5e-4 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=64 FED.local_epochs=2 EXP.project=lora-fedrec
python fedtrain.py data=ml-1m net=fedmf-lora-b net.init.gmf_emb_size=64 net.init.lora_rank=16 task_name=fedtrain-nb-scaling-init TRAIN.wandb=True TRAIN.lr=0.006 FED.agg_epochs=2000 TRAIN.weight_decay=5e-4 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=64 FED.local_epochs=2 EXP.project=lora-fedrec
python fedtrain.py data=ml-1m net=fedmf-lora-b net.init.gmf_emb_size=64 net.init.lora_rank=32 task_name=fedtrain-nb-scaling-init TRAIN.wandb=True TRAIN.lr=0.005 FED.agg_epochs=2000 TRAIN.weight_decay=5e-4 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=64 FED.local_epochs=2 EXP.project=lora-fedrec

# python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=32 task_name=fedtrain TRAIN.wandb=True TRAIN.lr=1e-1 FED.agg_epochs=2000 TRAIN.weight_decay=1e-4 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=1 compression=svd FED.compression_kwargs.rank=4
# python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=32 task_name=fedtrain TRAIN.wandb=True TRAIN.lr=1e-1 FED.agg_epochs=2000 TRAIN.weight_decay=1e-4 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=1 compression=svd FED.compression_kwargs.rank=2
# python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=32 task_name=fedtrain TRAIN.wandb=True TRAIN.lr=1e-1 FED.agg_epochs=2000 TRAIN.weight_decay=1e-4 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=1 compression=svd FED.compression_kwargs.rank=8
# python fedtrain.py data=ml-1m net=fedmf net.init.gmf_emb_size=32 task_name=fedtrain TRAIN.wandb=True TRAIN.lr=1e-1 FED.agg_epochs=2000 TRAIN.weight_decay=1e-4 TRAIN.log_interval=10 EVAL.interval=100 DATALOADER.batch_size=256 FED.local_epochs=1 compression=svd FED.compression_kwargs.rank=16
